### ISSUE TITLE
Remove inconsistent, expensive, unprofessional-looking self-health-check function

### ISSUE THREAD

**Issue by blueedgenick** [confluentinc/ksql-images#37]
PR https://github.com/confluentinc/ksql-images/pull/22, shortly prior to the CP5.4 release, added a new self-health-check function to the ksql-server image. This new function is invoked every 5 seconds by default (see https://github.com/confluentinc/ksql-images/blob/master/cp-ksql-server/Dockerfile.deb9#L41-L42) and works by posting a `show topics;` query to the running ksql server.
There are several problems with this:
1 - it is inconsistent with all the other CP docker images, with the possible exception of Connect which looks to have something similar added. This means that when you bring up a CP stack with `docker-compose up` and then check it's status with `docker-compose up`, only ksql-server (and ppossibly Connect) report their status as `Up (healthy)`. This gives the misleading impression that the other platform components are NOT healthy - a check like this needs to be all or none of the images. 
2 - running `show topics;` on a "real" cluster is potentially an expensive and time-consuming operation - certainly more than should be running every 5 seconds from every server.
3 - the "woohoo ksql is up!" message is less than professional looking
4 - the check runs too frequently (every 5 seconds by default) and spams the docker logs with verbose output at default logging levels
5 - this check is undocumented - you have to spelunk this private repo code to figure out how to adjust or disable it.

Example log output:

```
ksql-server        | [2020-01-17 01:46:29,759] INFO 127.0.0.1 - - [17/Jan/2020:01:46:29 +0000] "POST /ksql HTTP/1.1" 200 4000  81 (io.confluent.rest-utils.requests:62)
ksql-server        | [2020-01-17 01:46:34,982] INFO Received: KsqlRequest{ksql='SHOW TOPICS;', streamsProperties={}, commandSequenceNumber=Optional.empty} (io.confluent.ksql.rest.server.resources.KsqlResource:200)
ksql-server        | [2020-01-17 01:46:34,984] INFO AvroDataConfig values:
ksql-server        |    connect.meta.data = true
ksql-server        |    enhanced.avro.schema.support = false
ksql-server        |    schemas.cache.config = 1000
ksql-server        |  (io.confluent.connect.avro.AvroDataConfig:347)
```

**Comment by apurvam** [comment]
@rmoff would you mind picking this up? I would recommend running the command 'show streams' every 10 seconds. 

the message can be "KSQL is UP". 

This way we test that the ksql server is up and don't need to put an unnecessary load on Kafka. Presumably kafka has it's own healthchecks so we don't need to test it through ksql.

**Comment by mikebin** [comment]
Another issue with the current healthcheck is that it doesn’t appear to work in environments with RBAC which have basic auth enabled to the REST endpoint.

**Comment by strubbsel** [comment]
Another issue with the current healthcheck is that it doesn’t appear to work in environments with SSL client auth being enabled

**Comment by MichaelDrogalis** [comment]
Just to check: we can close this because we merged https://github.com/confluentinc/ksql-images/pull/45, right?

**Comment by mikebin** [comment]
@MichaelDrogalis - yes, the Docker healthcheck should be gone now.

**Comment by apurvam** [comment]
Great, thanks @mikebin
