### ISSUE TITLE
Unable to run on k8s with readOnlyRootFilesystem: true

### ISSUE THREAD

**Issue by PaulieMac** [confluentinc/ksql-images#51]
[This line](https://github.com/confluentinc/ksql/blob/41d7918a624c1ac52bb72647d7aec8e9965b757a/ksqldb-docker/src/include/docker/run#L20) and [this line](https://github.com/confluentinc/ksql/blob/41d7918a624c1ac52bb72647d7aec8e9965b757a/ksqldb-docker/src/include/docker/run#L32) apparently make it impossible to run on k8s with `readOnlyRootFilesystem: true`

It would be better if the templates were in a different dir (perhaps a parent) so we can mount a writable dir at the target site; as-is, this forces a less-secure deployment.

I am thinking that instead of this
```
dub template "/etc/ksqldb/ksqldb-server.properties.template" "/etc/ksqldb/ksqldb-server.properties"
```
maybe something like this?
```
dub template "/etc/ksqldb/ksqldb-server.properties.template" "/etc/ksqldb/config/ksqldb-server.properties"
```

**Comment by ricardo-aires** [comment]
Under the impression that every Confluent Docker Image makes the starting point at `/etc/confluent/docker/`.

**Comment by im-pratham** [comment]
check is this PR solves your issue https://github.com/confluentinc/ksql-images/pull/83/files.
I fixed of openshift. But same will be applicable to you
