### ISSUE TITLE
Version 6.1.0 has not been deployed to docker hub

### ISSUE THREAD

**Issue by javiersvg** [confluentinc/ksql-images#58]
I can only find version 6.0.0 on docker hub even though I think version 6.1.0 should be in docker hub.
https://hub.docker.com/r/confluentinc/cp-ksqldb-server/tags?page=1&ordering=last_updated&name=6

Am I doing something wrong?

**Comment by andrewegel** [comment]
6.1.0 versioned images were released last week - Nov 2020 only 6.0.0 was the latest release. I'm not sure where you got that information, but it was incorrect. 

Closing as non issue.
