### ISSUE TITLE
`ksql-tools.jar` not present in the `cp-ksqldb-server` image

### ISSUE THREAD

**Issue by danielpetisme** [confluentinc/ksql-images#60]
Hi, I wanted to try the KSQL migration tool but looks like the `confluentinc/cp-ksqldb-server` image does not embed the ksqldb-tools jar...
![image](https://user-images.githubusercontent.com/593564/125469984-1badaee0-a15b-4842-8cd2-0c46585dce7e.png)

By comparing the following pom's 
* https://github.com/confluentinc/ksql-images/blob/master/cp-ksqldb-server/pom.xml
* https://github.com/confluentinc/ksql/blob/master/ksqldb-docker/pom.xml
I can see the `ksqlsb-tools` dependency is not present in the first but it is in the latter.

**Comment by jzaralim** [comment]
Fixed in #62
