### ISSUE TITLE
why this ksql image does not support TIMESTAMP,DATE and TIME data type?

### ISSUE THREAD

**Issue by Taymindis** [confluentinc/ksql-images#85]
When i am using `confluentinc/ksqldb-server:0.23+` and it support timestamp data type.

But `cp-ksqldb-server:6.1.0` is not supporting and i got

`error resolve timestamp` error

**Comment by raphaelauv** [comment]
https://docs.confluent.io/platform/current/installation/versions-interoperability.html#ksqldb

confluent 6.1.0 is using ksqldb 0.14.0

**Comment by hrishabhg** [comment]
ksqldb-server:0.29+ is latest.
